### ISSUE TITLE
Error installing watchr gem

### ISSUE THREAD

**Issue by jonfuller** [mynyml/watchr#1]
---

C:\Users\jcfuller>gem install watchr --source=http://gemcutter.org
ERROR:  Error installing watchr:
##         watchr requires rev (>= 0.3.0, runtime)

C:\Users\jcfuller>gem install rev
Building native extensions.  This could take a while...
ERROR:  Error installing rev:
        ERROR: Failed to build gem native extension.

C:/Ruby/bin/ruby.exe extconf.rb install rev
checking for main() in c.lib... no
checking for HAVE_RB_IO_T in rubyio.h... no
creating Makefile

nmake
'nmake' is not recognized as an internal or external command,
## operable program or batch file.

Versions:
OS: Win7 x64
Ruby: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]
## Gem: 1.3.1

Looks like rev might work if I had nmake, but I'm having trouble finding nmake (at least a 64-bit version).

**Comment by mynyml** [comment]
Actually watchr will work on mswin without rev; it should only be a gem dependency on unix systems. I tried to make it a conditional dependency in the gemspec, but I can see now it won't work (the gem is built on the gem server, and being unix, the dependency is included). If I can't find a true fix by today, I'll update the gem with a workaround.

Thanks for the report, jonfuller

**Comment by mynyml** [comment]
I pushed a workaround (v0.5.4) that simply removes the rev dependency. Watchr falls back on the non-evented Portable event handler for now.

**Comment by mynyml** [comment]
Fixed in v0.5.5
Watchr will now automatically use rev on *nix if it's installed, but will not require it as a gem dependency. If it's not installed, it will simply fall back on the Portable handler.
