### ISSUE TITLE
captures seem to break on doze

### ISSUE THREAD

**Issue by rdp** [mynyml/watchr#10]
watch( 'lib/(.*).rb' )      {|md| }

works great on linux, on doze me seems to capture the entire thing.

doze:

MatchData "lib/regex_replace.rb" 1:"lib/regex_replace.rb"

linux:

MatchData "lib/regex_replace.rb" 1:"regex_replace"

If I get around to it I'll investigate it.
-r

**Comment by rdp** [comment]
Turns out to be reproducible with jruby (only) in both doze and linux.  
I'll ask them about it.
http://jira.codehaus.org/browse/JRUBY-4558

**Comment by rdp** [comment]
looks like they've fixed it upstream. Should be good now.
Thanks!

**Comment by mynyml** [comment]
Good catch!
