### ISSUE TITLE
Suboptimal command line in Rakefile to run tests

### ISSUE THREAD

**Issue by vvs** [mynyml/watchr#11]
See http://jira.codehaus.org/browse/JRUBY-4557

I'd suggest to replace system command in Rakefile by the following:

require 'rbconfig'
  RUBY = File.join([Config::CONFIG['bindir'], Config::CONFIG['ruby_install_name']]) << Config::CONFIG['EXEEXT']

exit system(%Q{#{RUBY} -v -rubygems -I.:lib -e"%w( #{tests.join(' ')} ).each {|file| require file }"})

That would properly launch the correct ruby interpreter, and would work with MRI _and_ JRUBY.

**Comment by mynyml** [comment]
Thanks for the tip, will patch.

**Comment by mynyml** [comment]
Fix rake test task for jruby/mswin. Closed by 77bd4ccdb540cec96c7a93de855c6a6f6213852c

Solution by @vvs
