### ISSUE TITLE
Watchr::Script not firing block?

### ISSUE THREAD

**Issue by juliocesar** [mynyml/watchr#13]
Hey ya,

I'm trying to use watchr to just watch a file from inside IRb, as in:

```
$ irb -r watchr
>> s = Watchr::Script.new
...
>> s.watch('tmp/foo') { STDOUT.puts "change in foo detected" }
```

I then modify "tmp/foo", but nothing happens. What am I missing?

Thanks!

**Comment by mynyml** [comment]
To actually watch the files, watchr needs to enter into an event loop (calling the handlers' reactors). That's done with Controller#run. If you did that within irb though it would just block and prevent you from actually using irb. You'll have to fire up another shell and run watchr in there to achieve what you want.

You might want to use `watchr -e` for quick one off watches. Try `watchr --help` for more info.
