### ISSUE TITLE
Allow 'watch' to take a glob

### ISSUE THREAD

**Issue by dstrelau** [mynyml/watchr#14]
This is a way-backwards incompatible change, but I thought I'd throw it out there, just in case anyone is interested.

I've changed watch to take either a true Regexp object or a String, which is passed to Dir.glob. When you use a Regexp, you get passed match data, just as before. When using a String, you just get a string with the filename. This means the following are now equivalent:

```
watch %r{test\/.*/.*_test\.rb} {|match| system "ruby #{match[0]}" }
watch 'test/**/*_test.rb' {|file| system "ruby #{file}" }
```

I know it's breaks all sorts of things, but it means for simple patterns, you don't have to deal with escaping regexps and such.

dstrelau/watchr@f976c6

**Comment by mynyml** [comment]
You're right about it breaking all sorts of things :) I agree that it's simpler for some patterns, but it's conceptually more complex for the interface as a whole. I think it'd make a nice plugin though.

**Comment by powcloud** [comment]
Does the base watchr support globs?  Seems this is needed for any projects with some level of size/structure/complexity.

**Comment by dstrelau** [comment]
@powcloud: no, it currently takes a regexp (as as string) to match against the full filepath.

**Comment by trans** [comment]
I have an idea for a generalized multi-argument watch interface:

```
watch(regex, glob, ...){ |match, file, ...|  ... }
```

The multi-args would either fit together as if '+' together, or File.join together --not sure which yet, but in any case this interface would be super flexible. e.g.

```
watch(/^(lib|ext)/, '**', '*.rb'){ |_, dir, file| ruby "test/#{dir}/test_#{file}" }
```
