### ISSUE TITLE
Ability to gem-ify watchr scripts

### ISSUE THREAD

**Issue by rsanheim** [mynyml/watchr#2]
heya

I have a little gem called [watch-me-now](http://github.com/rsanheim/watch-me-now/) that builds on watchr to wrap up simple patterns for testing most gems/libraries/plugins I've been writing or editing lately.  My goal is to have common, reusable patterns there for testing, while still allowing extension.  I've had it working through various hacks, but right now its broken for the most part:

My first problem is that the .watchr script defines the methods at the top level, but those methods don't actually exist at the top level.  This means when the watchr bin script tries to require the file from the gem, it immediately raises a NoMethodError on `watch` and dies.  

Is there a better way to do this type of thing?  It seems you already thought of it with the 'potentially with gem' stuff in watchr.  Maybe I should create a Watchr::Script myself instead?

Thanks for the nice tool, btw...
- Rob

**Comment by mynyml** [comment]
Hi,
the #potentially_with_gem part was meant to be used differently, but it's unnecessary so I removed it. I tested watch-me-now and it works fine on the latest watchr commit.

Thank you for testing that part of the code!

**Comment by rdp** [comment]
http://wiki.github.com/mynyml/watchr/running-programmatically

might help
