### ISSUE TITLE
Dropped events when using watchr + ruby-fsevent on Mac OS X 10.6.6

### ISSUE THREAD

**Issue by al-the-x** [mynyml/watchr#20]
I'm not sure if anyone else is noticing this, but I've encountered some problems running "watchr" with "ruby-fsevent". It appears as though watchr isn't filtering the events passed to it correctly or something. When I save a file in the watch list, every third time or so, nothing happens. Running with the debug enabled, I can see watchr intercepting certain FSEvent signals, but they're the wrong signals... They're out of sync with what's happening on the filesystem.

It's almost as if there is a queue of events that is being popped, and watchr is just examining the next one on the queue and waiting for another event to trigger another pop. It's not popping events until it encounters an interesting one, maybe?

**Comment by Burgestrand** [comment]
ruby-fsevent has some issues with ruby 1.9, also mentioned in issue #16. For me, it simply fired change-events for the wrong files, also reporting an error. As a result, I stopped using it.

**Comment by al-the-x** [comment]
My ruby is 1.8.7, and I've come to the same conclusion. I'm using Watchr::EventHandler::Portable instead, which relies on the "rev" gem, I think...?
