### ISSUE TITLE
[feature request] redo last action

### ISSUE THREAD

**Issue by ariera** [mynyml/watchr#31]
When I'm testing I find my self adding an space (or a new line, or any irrelevant modification to the code) to the test and saving it just to trigger watchr.

I would love to be able to trigger a redo of the las test in the console by doing something like "cmd + r" or any key combination.

Does anybody else find this useful? do you use any other trick?

**Comment by mpartel** [comment]
The readme suggests you can `Signal#trap` in your watchr script. Maybe make a global shortcut invoke a script that sends, say, SIGUSR1 to watchr.

**Comment by ariera** [comment]
Great idea, I just did that and works perfectly.
I wrote a mini-guide with the steps in case anybody is interested: https://gist.github.com/1139285
