### ISSUE TITLE
Watchr stops watching a file after some minutes

### ISSUE THREAD

**Issue by felds** [mynyml/watchr#38]
If you take more than a minute or two, Watchr stops watching the file.

In order for it to work I have to stop watchr, start it again, edit the file and then save it again.

The same thing is happening on my two Macs (both with OSX 10.6).

**Comment by tricktracker** [comment]
Has anyone found a solution yet? I have the same issue on MacOS Snow Leopard

**Comment by phaseOne** [comment]
Same problem on Lion 10.7.4

**Comment by danielcha** [comment]
Same problem on Ubuntu 10.04

**Comment by SpadXIII** [comment]
Same problem for me on ubuntu 11.04
I use this with twitter bootstrap, so the command is :

```
watchr -e "watch('less/.*\.less') { system 'make' }"
```

This seems to create a temp file in /tmp with the command in there. This file is deleted after a few minutes, effectively stopping watchr.

@see also https://github.com/mynyml/watchr/pull/26

**Comment by danielcha** [comment]
@SpadXIII yeah I'm using it with bootstrap too! Maybe there cases are related somehow...

**Comment by Johnny5k** [comment]
Same here, using it with bootstrap. Any suggestions?
