### ISSUE TITLE
occasional crashing on file save

### ISSUE THREAD

**Issue by cloudhead** [mynyml/watchr#4]
Occasionally, say one in ten times I save one of my watched files (in this case _toto.rb_), watchr will crash with this error:

```
/usr/local/lib/ruby/1.9.1/pathname.rb:801:in `mtime': No such file or directory - /usr/local/src/toto/lib/toto.rb (Errno::ENOENT)
    from /usr/local/lib/ruby/1.9.1/pathname.rb:801:in `mtime'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:44:in `block in detect_event'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:44:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:44:in `max'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:44:in `detect_event'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:24:in `trigger'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:19:in `block in listen'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:19:in `loop'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/event_handlers/portable.rb:19:in `listen'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/lib/watchr/controller.rb:38:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/watchr-0.5.7/bin/watchr:76:in `<top (required)>'
    from /usr/local/bin/watchr:19:in `load'
    from /usr/local/bin/watchr:19:in `<main>'
```

Of course, the file does actually exist, and when I restart watchr and save the file, it works. This is on OS X 10.6.2.

**Comment by mynyml** [comment]
I can't reproduce on linux. It's not clear to me why the error is even raised, given that there's a rescue Errno::ENOENT statement in that method..

Meanwhile, you can use the rev handler instead (your stack trace says you're using the portable handler). Simply install rev (gem install rev) and it'll pick it up automatically.

Thanks for the report. I don't have access to an osx box so it might take some time, but I'll see what I can do.

**Comment by cloudhead** [comment]
Ok, so I've been having the same weird issue with my own (less) gem, which uses mtime and such — so I'm thinking this isn't a gem problem, but might have to do with OSX.

**Comment by pvande** [comment]
I have been seeing this same problem under a CentOS 4 Linux installation.

**Comment by mynyml** [comment]
I still haven't seen this error under ubuntu Jaunty & Karmic. cloudhead's stacktrace mention's ruby 1.9.1 though, and I mostly run watchr under 1.8.7. @pvande: what ruby version are you using?

If someone had steps to reproduce that would be perfect, of course, but if someone could provide more details it would be great too.

**Comment by pvande** [comment]
I'm running ruby 1.8.5 (and I was running watchr 0.5.7 -- I've upgraded now).  It's not a problem that's easy to reproduce; it will simply die, apparently randomly, when a file is saved.  I did notice it somewhat more frequently after rapid successive saves than in casual use.

**Comment by mynyml** [comment]
@pvande are you using the Rev handler or Portable handler? (watchr -d will tell you if you're unsure)

**Comment by pvande** [comment]
I'm not sure...

```
[pvande]$ watchr -d
Usage: watchr [opts] path/to/script
```

**Comment by mynyml** [comment]
Sorry, I should have been more specific. Try

<pre>
  $ watchr -d path/to/your/script
</pre>

If it says `using Watchr::EventHandler::Portable handler`, could you try to install Rev (`gem install rev`) and see if the bug still occurs?

**Comment by pvande** [comment]
I am using the EventHandler notifier, but I can't install Rev because it depends on a more recent version of Ruby (>= 1.8.6).  Unfortunately, upgrading the installed Ruby is likewise not possible.

**Comment by mynyml** [comment]
I still haven't been able to reproduce or seen the error occured. I'm gonna close, but feel free to reopen if you have steps to reproduce, or more information.
