### ISSUE TITLE
feature request: in debug mode output files as they're listed

### ISSUE THREAD

**Issue by rdp** [mynyml/watchr#9]
ex:

E:\installs\ruby191p376\lib\ruby\gems\1.9.1\gems\redcar-0.3.2dev>watchr -d go.watchr
[watchr debug] using Watchr::EventHandler::Portable handler
[watchr debug] loaded script file "E:/installs/ruby191p376/lib/ruby/gems/1.9.1/gems/redcar-0.3.2dev/go.watchr"
[watchr debug] got changed file with matches [xxx, xxx, xxx]
 # then run it

I'd be happy to submit a patch for such if it has a chance of being accepted.

Thanks!
-r

**Comment by mynyml** [comment]
Sounds like reasonable additional information for debug mode. I'd apply the patch.
Maybe something like `"[watchr debug] received #{event_type} event for #{path}"` ?

**Comment by rdp** [comment]
looks reasonable
